services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    networks:
      - nest_network

  db:
    image: postgres:15
    container_name: nest_postgres
    restart: always
    environment:
      POSTGRES_USER: nest_user
      POSTGRES_PASSWORD: nest_password
      POSTGRES_DB: nest_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest_network

volumes:
  postgres_data:

networks:
  nest_network:
    driver: bridge
